# This is a basic workflow to help you get started with Actions

name: "CI: Test and Build"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout
      
      # Sets up node with a specified version
      - uses: actions/node-setuo@v2
        name: Setup Node
        with:
          node-version: 16 

      - name: Install Packages
        run: npm ci
        
      - name: Test code
        run: npm run test
        
      - name: Build Code
        run: npm run build
